# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consumed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('tot_fat', models.FloatField()),
                ('tot_protein', models.FloatField()),
                ('sugar', models.FloatField()),
                ('tot_carbs', models.FloatField()),
                ('fat_saturated', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sodium', models.FloatField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_obj', models.IntegerField()),
                ('carbs_obj', models.IntegerField()),
                ('protein_obj', models.IntegerField()),
                ('fat_obj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reg_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date_birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('cp', models.IntegerField()),
                ('tags', models.CharField(max_length=180)),
            ],
        ),
        migrations.AddField(
            model_name='objectives',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Reg_User'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Item'),
        ),
        migrations.AddField(
            model_name='histories',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Item'),
        ),
        migrations.AddField(
            model_name='histories',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Reg_User'),
        ),
    ]
