# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consumed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique='true')),
                ('calories', models.FloatField(default=0.0)),
                ('tot_fat', models.FloatField(default=0.0)),
                ('tot_protein', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('tot_carbs', models.FloatField(default=0.0)),
                ('fat_saturated', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('sodium', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_obj', models.IntegerField()),
                ('carbs_obj', models.IntegerField()),
                ('protein_obj', models.IntegerField()),
                ('fat_obj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_birth', models.DateField(null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('cp', models.IntegerField(null=True)),
                ('tags', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='objectives',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Items'),
        ),
        migrations.AddField(
            model_name='histories',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Items'),
        ),
        migrations.AddField(
            model_name='histories',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
