# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20171130_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('calories', models.FloatField()),
                ('tot_fat', models.FloatField(default=None)),
                ('tot_protein', models.FloatField(default=None)),
                ('sugar', models.FloatField(default=None)),
                ('tot_carbs', models.FloatField(default=None)),
                ('fat_saturated', models.FloatField(default=None)),
                ('fiber', models.FloatField(default=None)),
                ('sodium', models.FloatField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reg_User',
            new_name='Reg_Users',
        ),
        migrations.AlterField(
            model_name='histories',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Items'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Items'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
