# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20171206_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='calories',
            field=models.FloatField(default=None),
        ),
    ]
