# Generated by Django 2.0 on 2017-12-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20171206_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histories',
            new_name='History',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Objectives',
            new_name='Objective',
        ),
    ]
