# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20171206_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='fat_saturated',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='tot_carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='tot_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='tot_protein',
            field=models.FloatField(default=0.0),
        ),
    ]
